#Feel Free To Edit This As Best As You Can
print("write your list dont paste it write it")
print("To Exit keep hitting Enter")

a = raw_input("Here :")
b = raw_input("Here :")
c = raw_input("Here :")
d = raw_input("Here :")
e = raw_input("Here :")
lokl = raw_input("Here :")
g = raw_input("Here :")
h = raw_input("Here :")
i = raw_input("Here :")
j = raw_input("Here :")
k = raw_input("Here :")
l = raw_input("Here :")
m = raw_input("Here :")
n = raw_input("Here :")
o = raw_input("Here :")
p = raw_input("Here :")
q = raw_input("Here :")
r = raw_input("Here :")
s = raw_input("Here :")
t = raw_input("Here :")
u = raw_input("Here :")
v = raw_input("Here :")
w = raw_input("Here :")
x = raw_input("Here :")
y = raw_input("Here :")
z = raw_input("Here :")
bo = raw_input("Here :")
jo = raw_input("Here :")
fo = raw_input("Here :")
go = raw_input("Here :")
mp = raw_input("Here :")
sv = raw_input("Here :")
po = raw_input("Here :")
zed = raw_input("Here :")
kilo= raw_input("Here :")
pottuss = raw_input("Here :")
weed = raw_input("Here :")
chfita = raw_input("Here :")
bob = raw_input("Here :")
vigini = raw_input("Here :")
lambo = raw_input("Here :")
rgini = raw_input("Here :")
fini = raw_input("Here :")
dio = raw_input("Here :")
hini = raw_input("Here :")
deg = raw_input("Here :")
reg = raw_input("Here :")
bgt = raw_input("Here :")
zr = raw_input("Here :")
ezd = raw_input("Here :")
sqds = raw_input("Here :")
df = raw_input("Here :")
dsfdsf = raw_input("Here :")
sgftuy = raw_input("Here :")
uui = raw_input("Here :")
ukjuk = raw_input("Here :")
hjkhj = raw_input("Here :")
klmp = raw_input("Here :")


lov = [a, b, c, d, e, lokl, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, bo, jo, fo, go, mp, sv, po, zed,kilo,pottuss,weed,chfita,bob,vigini,lambo,rgini,fini,dio,hini,deg,reg,bgt,zr,ezd,sqds,df,dsfdsf,sgftuy,uui,ukjuk,hjkhj,klmp]
for i in lov:
 f = open('List.txt','a')
 if i != "exitt" :
  f.write('\n' + a + i)
  f.write('\n' + b + i)
  f.write('\n' + c + i)
  f.write('\n' + d + i)
  f.write('\n' + e + i)
  f.write('\n' + lokl + i)
  f.write('\n' + g + i)
  f.write('\n' + h + i)
  f.write('\n' + i + i) 
  f.write('\n' + j + i) 
  f.write('\n' + k + i)
  f.write('\n' + l + i) 
  f.write('\n' + m + i) 
  f.write('\n' + n + i) 
  f.write('\n' + o + i) 
  f.write('\n' + p + i) 
  f.write('\n' + q + i) 
  f.write('\n' + r + i) 
  f.write('\n' + s + i) 
  f.write('\n' + t + i) 
  f.write('\n' + u + i) 
  f.write('\n' + v + i) 
  f.write('\n' + w + i)
  f.write('\n' + x + i) 
  f.write('\n' + y + i) 
  f.write('\n' + z + i)
  f.write('\n' + bo + i)
  f.write('\n' + jo + i)
  f.write('\n' + fo + i)
  f.write('\n' + go + i)
  f.write('\n' + mp + i)
  f.write('\n' + sv + i)
  f.write('\n' + po + i)
  f.write('\n' + zed + i)
  f.write('\n' + kilo + i)
  f.write('\n' + pottuss + i)
  f.write('\n' + chfita + i)
  f.write('\n' + weed + i)
  f.write('\n' + bob + i)
  f.write('\n' + vigini + i)
  f.write('\n' + lambo + i)
  f.write('\n' + rgini + i)
  f.write('\n' + hini + i)
  f.write('\n' + fini + i)
  f.write('\n' + dio + i)
  f.write('\n' + deg + i)
  f.write('\n' + reg + i)
  f.write('\n' + bgt + i)
  f.write('\n' + zr + i)
  f.write('\n' + ezd + i)
  f.write('\n' + sqds + i)
  f.write('\n' + df + i)
  f.write('\n' + dsfdsf + i)
  f.write('\n' + sgftuy + i)
  f.write('\n' + uui + i)
  f.write('\n' + ukjuk + i)
  f.write('\n' + hjkhj + i)
  f.write('\n' + klmp + i)
 f.close()
with open('List.txt') as infile, open('FList.txt', 'w') as outfile:
    for line in infile:
        if not line.strip(): continue  
        outfile.write(line)
print('the list is saved as FList.txt')
print('PoTtUsS')
exit()
